### ISSUE TITLE
Driver not loaded when executed from a different path

### ISSUE THREAD

**Issue by ciphray** [cocafe/physmem#1]
Very nice work on the application, love how fast it operates (much like msr-cmd).

One minor problem I've come across is, unlike msr-cmd this will not load the driver if you do not execute it from in the same path as the exe
![physram-path](https://user-images.githubusercontent.com/19839730/178148805-8d9bbd54-5094-419a-8368-953b92714006.png)

Any chance you'd be able to fix this? 

Not a huge deal if not, already very useful as is.
Thanks

**Comment by cocafe** [comment]
👌 maybe the logical of loading driver needs to change a bit

**Comment by cocafe** [comment]
Should have fixed with this commit f8edb55dc421bfeaa87e2e6f816efbfccc562e43 .

Driver was looked up by CWD instead of process image path.
