### ISSUE TITLE
which version is better?

### ISSUE THREAD

**Issue by pexcn** [cocafe/physmem#3]
Hello @cocafe:

First of all, thank you for your program, which makes the PL1/PL2 settings of my laptop take effect immediately.
And I found two versions of the program, `asmmap64` and `inpoutx64`, in the release.
I tested them both and they all work normally. But which one is better? Which one should I use?

Sing Yu
Cheers.

**Comment by cocafe** [comment]
Both can do the job, but I remember that inpoutx64 has some troubles on uninstalling it, while asmmap64 does not.
Both are vulnerable, any programs can RW whole RAM even without administrator privilege. 
Uninstall them when RW are done, ...or you can try to use other utility to unload win driver.

**Comment by pexcn** [comment]
Okay, safety is not important to me, so I think `asmmap64` version seems better for me.
Thank you. :)
